version: "3.9"

services:
  haproxy:
    image: docker.io/library/haproxy:latest
    restart: always
    volumes:
      - /etc/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "80:80"
      - "443:443"
      - "6443:6443"
      - "70:70" # haproxy admin console, login with user:pass
