[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http.redirections.entryPoint]
      to = "websecure"
      scheme = "https"
      permanent = true

  [entryPoints.websecure]
    address = ":443"

  [entryPoints.kubernetes]
    address = ":6443"

[log]
  level = "INFO"
  format = "json"

[accessLog]

[api]
  dashboard = true

[metrics]
  [metrics.prometheus]
    addEntryPointsLabels = true
    addRoutersLabels = true
    addServicesLabels = true

[providers]
  [providers.file]
    directory = "/etc/traefik/dynamic"
    watch = true

  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    exposedByDefault = false

[certificatesResolvers.le.acme]
  email = "automater.helper@gmail.com"
  storage = "/certificates/acme.json"
  [certificatesResolvers.le.acme.httpChallenge]
    # used during the challenge
    entryPoint = "web"
