version: '3.9'

services:
  portainer:
    image: docker.io/portainer/agent:latest
    container_name: agent.portainer
    restart: always
    ports:
      - '9001:9001'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
