# This workflow updates labels for issues and pull requests.
# It is supposed to be run on each push to "main".

name: Update labels

on:
  push:
    branches:
      - "main"

jobs:
  upload-labels:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - id: labels-changed
      run: |
        if git diff --name-only HEAD~1 HEAD | grep -q ".github/labels.yaml"; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
    - uses: actions/setup-go@v4
      if: steps.labels-changed.outputs.changed == 'true'
      with:
        go-version: '1.20'
    - if: steps.labels-changed.outputs.changed == 'true'
      run: go install github.com/shanduur/labeler/cmd/labeler@main
    - if: steps.labels-changed.outputs.changed == 'true'
      run: labeler upload --owner miriady --repo infrastructure ./.github/labels.yaml
      env:
        LABELER_TOKEN: ${{ secrets.LABELER_TOKEN }}